spring.application.name=iternaryrate
spring.datasource.url=jdbc:mysql://localhost:3306/iternaryrate
spring.datasource.username=root
spring.datasource.password=June1$t61

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

